--- #YAML:1.0
name:               AutoRole
version:            0.03
abstract:           Compiletime OR runtime mixin of traits/roles/mixins/your-word-here.
author:
    - Paul Seamons
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
